### ISSUE TITLE
style: add `.pre-commit-config.yml`

### ISSUE THREAD

**Issue by SauravMaheshkar** [KAIR-BAIR/nerfacc#117]
I noticed that most of (if not all) the steps of the CI checks can be enforced via [pre-commit](https://pre-commit.com/). Having [pre-commit](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

This is a simple proposal for the config file

```YAML
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.8.12
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
```
